# Generated by Django 5.2.3 on 2025-06-27 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_advertisement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
    ]
